shared:
  api_key: <%= ENV["NEXOSIS_API_KEY"] %>
development:
  secret_key_base:  '<%= ENV["DEV_SECRET_KEY"] %>'
test:
  secret_key_base: '<%= ENV["TEST_SECRET_KEY"] %>'
production:
  secret_key_base: '<%= ENV["PROD_SECRET_KEY"] %>'