shared:
    api_key: <%= ENV["NEXOSIS_API_KEY"] %>
development:
  secret_key_base:  [generate something with 'rake secret']

test:
  secret_key_base:  [generate something with 'rake secret']

production:
  secret_key_base: [generate something with 'rake secret']